### ISSUE TITLE
Can you please help to run this project code

### ISSUE THREAD

**Issue by nishachalingal** [mpc001/Visual_Speech_Recognition_for_Multiple_Languages#14]
Am begginer
in python 
Select this topic as project in my final year and Using ubuntu version

Wher i want to give path of models in this givencode

**Comment by M1ndBlast** [comment]
Hey there.

I already installed requirements, model and language model.

I wonder which video format I must have. I'm using mp4 files and I get next error

```
(autoavsr) PS D:\Visual_Speech_Recognition_for_Multiple_Languages> python .\infer.py config_filename=.\configs\LRS3_V_WER19.1.ini data_filename=.\Grabacion.mp4 detector=mediapipe
Error executing job with overrides: ['config_filename=.\\configs\\LRS3_V_WER19.1.ini', 'data_filename=.\\Grabacion.mp4', 'detector=mediapipe']
Traceback (most recent call last):
  File ".\infer.py", line 15, in main
    output = InferencePipeline(cfg.config_filename, device=device, detector=cfg.detector, face_track=True)(cfg.data_filename, cfg.landmarks_filename)
  File "D:\Visual_Speech_Recognition_for_Multiple_Languages\pipelines\pipeline.py", line 45, in __init__
    self.model = AVSR(modality, model_path, model_conf, rnnlm, rnnlm_conf, penalty, ctc_weight, lm_weight, beam_size, device)
  File "D:\Visual_Speech_Recognition_for_Multiple_Languages\pipelines\model.py", line 43, in __init__
    self.token_list = ['<blank>'] + [word.split()[0] for word in open(file_path).read().splitlines()] + ['<eos>']
  File "C:\Users\peduz\miniconda3\envs\autoavsr\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4416: character maps to <undefined>

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

Can u help me?
